development:
  username: pimpim
  password: pim123
  politiki_uri: "http://localhost:3000/api/"
  amqp_url: "amqp://admin:admin123@localhost/politiki_dev"
  database:
    adapter: jdbcmysql
    database: politiki_bi
    username: politiki_bi
  olap:
    driver: mysql
    host: localhost
    database: politiki_bi
    username: politiki_bi

test:
  username: pimpim
  password: pim123
  politiki_uri: "http://localhost:3000/api/"
  amqp_url: "amqp://admin:admin123@localhost/politiki_dev"
  database:
    adapter: jdbcmysql
    database: politiki_bi_test
    username: politiki_bi
  olap:
    driver: mysql
    host: localhost
    database: politiki_bi_test
    username: politiki_bi
    password:

production:
  database:
    adapter: mysql2
    database: politiki_bi
    username: politiki_bi